### ISSUE TITLE
cannot restore

### ISSUE THREAD

**Issue by sandbox404** [m1stadev/Inferius#33]
hello,  I want to downgrade my iPhone 8 from 14.6 to 14.3, but encounter some errors.
what should I do next?

the output of inferius: 
[7] Restoring...
Traceback (most recent call last):
  File "./inferius", line 152, in <module>
    main()
  File "./inferius", line 148, in main
    restore_ipsw(api, buildmanifest, custom_ipsw, args.update, tmpdir)
  File "./inferius", line 87, in restore_ipsw
    restore.restore(ipsw_path, device.baseband, updating)
  File "/Users/cyanide/Desktop/Inferius-master/utils/restore.py", line 40, in restore
    if 'Done: restoring succeeded!' not in futurerestore.stdout:
TypeError: argument of type 'NoneType' is not iterable

the futurerestore log: 
Extracting iBEC.d20.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (1438354 bytes)...
waiting for device to reconnect... Cleaning up...
[exception]:
what=failed to reconnect to device in recovery (iBEC) mode

code=65863697
line=1005
file=futurerestore.cpp
commit count=196:
commit sha  =e6c21f160eae23f9fab240fa088b0dcffca0e6b2:
Done: restoring failed!

**Comment by viccy5022** [comment]
dear do you have been solve it? thanks
