### ISSUE TITLE
Downgrade to iOS 14 error 

### ISSUE THREAD

**Issue by D0lcegabbana** [m1stadev/Inferius#44]
Hello.
i have an iphone x with ios 14.7.1
iphone 8 with ios 14.6 and  iPhone  7 plus with ios 15
  I am trying to downgrade the firmware to 14.7.1 but I get the error:

cat@iMac-cat Inferius-master 2 % ./inferius -d iPhone9,2 -f /Users/cat/Desktop/Inferius-master\ 2/IPSW/iPhone_5.5_P3_14.7.1_18G82_Restore_custom.ipsw -r  
Restoring custom IPSW
[1] Verifying custom IPSW...
[2] Checking for device in pwned DFU...
[3] Extracting bootchain...
[4] Signing bootchain...
[5] Sending bootchain...
[6] Saving SHSH blobs...
[7] Restoring...
Traceback (most recent call last):
  File "./inferius", line 158, in <module>
    main()
  File "./inferius", line 154, in main
    restore_ipsw(api, buildmanifest, custom_ipsw, args.update, tmpdir, blob, signing_blob)
  File "./inferius", line 93, in restore_ipsw
    restore.restore(ipsw_path, device.baseband, updating)
  File "/Users/cat/Desktop/Inferius-master 2/utils/restore.py", line 39, in restore
    if 'Done: restoring succeeded!' not in futurerestore.stdout:
TypeError: argument of type 'NoneType' is not iterable
cat@iMac-cat Inferius-master 2 %

**Comment by vadimszzz** [comment]
futurerestore must be downloaded from link in README

**Comment by D0lcegabbana** [comment]
> futurerestore must be downloaded from link in README

I downloaded compiled  inferius from your repo .it include futurerestore in folder.

**Comment by vadimszzz** [comment]
Looks like issue is in this lines:

https://github.com/vadimszzz/Inferius/blob/master/utils/restore.py#L33-40

**Comment by D0lcegabbana** [comment]
> Looks like issue is in this lines:
> 
> https://github.com/vadimszzz/Inferius/blob/master/utils/restore.py#L33-L40

Вадим ,ты пробовал откат  на 14?  Future restore  все время ругается на appnonce
Генератор в айфоне и в блобсах совпадает .

**Comment by vadimszzz** [comment]
> > Looks like issue is in this lines:
> > https://github.com/vadimszzz/Inferius/blob/master/utils/restore.py#L33-L40
> 
> Вадим ,ты пробовал откат на 14? Future restore все время ругается на appnonce Генератор в айфоне и в блобсах совпадает .

Нет не получилось, забил хуй и купил телефон новый. Больше не буду фиксить этот проект

**Comment by viccy5022** [comment]
Did you solve the problem？ I have the same problem。

**Comment by D0lcegabbana** [comment]
> Did you solve the problem？ I have the same problem。

I compiled all dependence and now have another error .

**Comment by viccy5022** [comment]
What is the mistake？
